= CloudBees action: Manage artifact version labels

Use this action to create, update, and remove labels on existing artifact versions in the CloudBees platform.
To learn more about organizing your artifacts using labels, refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/artifacts#labels[Artifact labels].

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `artifact-id`
| String
| Yes
| The unique identifier of an artifact version reported to the CloudBees platform.

| `labels`
| String
| Yes
| A comma-separated list of artifact labels.

| `operation`
| String
| No
| The labelling activity to be performed.
The following options are valid:

* `ADD`, to apply label(s).
* `REMOVE`, to remove label(s).
The default is `ADD`.

|===

== Usage examples

The following basic example adds the labels `For Production` and `Testing Passed` to an existing artifact version:

[source,yaml]
----
jobs:
    add_labels_to_artifact_version:
        steps:
          - name: add_labels_to_artifact_version
            uses: cloudbees-io/label-artifact-version@v1
            with:
              artifact-id: 1234abcd-56ef-78gh-90ij-klmnop123456
              labels: For Production,Testing Passed

----

In the following example, an artifact version has been labelled with `Label1`, `Label2`, and `Label3`.
Invoking this action removes the `Label2` and `Label3` labels, so that the artifact version remains labelled only with `Label1`.

[source,yaml]
----
        steps:
        - name: Unlabel an artifact version
          uses: cloudbees-io-gha/label-artifact-version@v1
          with:
            artifact-id: 1234abcd-56ef-78gh-90ij-klmnop123456
            labels: Label2,Label3
            operation: REMOVE

----


== License

This code is made available under the
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
