apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: LabelArtifactVersion
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  success_remove_labels_to_artifact_ver:
    steps:
      - name: success_remove_labels_to_artifact_ver
        uses: cloudbees-io/label-artifact-version@main
        with:
          component-id: "065b2595-cd1e-415d-9c5b-cab06074b641"
          name: "artifactService"
          version: "v1.0.0"
          labels: "Enter"
          operation: "REMOVE"
