apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: LabelArtifactVersion
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  success_default_add_labels_to_artifact_ver:
    steps:
      - name: success_default_replace_labels_to_artifact_ver
        uses: cloudbees-io/label-artifact-version@main
        with:
          artifact-id: "ea07033d-3008-40ec-9e50-a0efce7493d8"
          labels: "Default,     ADD, operation , performed."