apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: LabelArtifactVersion
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  success_default_add_labels_to_artifact_ver:
    steps:
      - name: success_default_replace_labels_to_artifact_ver
        uses: cloudbees-io/label-artifact-version@main
        with:
          artifact-id: "f089759c-9a6c-4c5b-befb-d70ca006625c"
          labels: "Default,     ADD, operation , performed."